name: Deploy to shinyapps.io
on:

  # run on any push
  push:

  # run on request (via button in actions menu)
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to shinyapps.io

    # allow skipping deployment for commits containing '[automated]' or '[no-deploy]' in the commit message
    if: "!contains(github.event.head_commit.message, '[automated]') && !contains(github.event.head_commit.message, '[no-deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: DivadNojnarg/shinyapps-deploy-github-action@v2
        with:
          # account and application name (https://<accountName>.shinyapps.io/<appName>)
          appName: "shinyMonsUgly"
          accountName: "dgranjon"

          # token and secret obtained from https://www.shinyapps.io/admin/#/tokens
          accountToken: ${{ secrets.SHINYAPPS_TOKEN }}
          accountSecret: ${{ secrets.SHINYAPPS_SECRET }}
